version: 2.1
jobs:
  blog_api_deployment_process:
    docker:
      - image: cimg/node:19.8.1
    steps:
      - checkout
      - run:
          name: npm update
          command: sudo npm install -g npm@latest
      - run:
          name: run automated tests
          command: npm test


workflows:
  blog-demo: 
    jobs:
      - blog_api_deployment_process